#%RAML 1.0
title: OpenStreepMap
baseUri: https://www.openstreetmap.org
version: v0.7

uses: 
  data/pets.raml

traits: 
    /locations
    get:
      description: get the location of all pets lost and found 
      headers: 
        keyForAcces: StringOfCharacters
        body: 
        responses: 
            200: 
                body:
                    aplication/JSONResponse:
                        {
                            lat:Float,
                            lon:Float,
                            locationName:String
                        }

            404: 
                body: Not Found/No entry in database
            401:Unauthorized
    /locations/found
        get:
        description: get the location of all founded pets 
        headers: 
            keyForAcces: StringOfCharacters
            body: 
            responses: 
                200: 
                    body:
                        aplication/JSONResponse:
                            {
                                lat:Float,
                                lon:Float,
                                locationName:String
                            }

                404: 
                    body: Not Found/No entry in database
                401:Unauthorized
    /locations/lost
        get:
        description: get the location of all lost pets 
        headers: 
            keyForAcces: StringOfCharacters
            body: 
            responses: 
                200: 
                    body:
                        aplication/JSONResponse:
                            {
                                lat:Float,
                                lon:Float,
                                locationName:String
                            }

                404: 
                    body: Not Found/No entry in database
                401:Unauthorized
    /locations/{petId}
    get:
        description: get the location of a specific pet base on id
        headers: 
        body:  
        responses:
            200: 
                body:
                    aplication/JSONResponse:
                        {
                            lat:Float,
                            lon:Float,
                            locationName:String
                        }  
            401:Unauthorized
    /addLostPets/{id}
    post:
        description: Add location for a pet
        headers: 
        body: 
        responses:
         200:
            body: Location was added as "Lost at"
                aplication/JSONResponse:
                        {   
                            petId
                            lat:Float,
                            lon:Float,
                            locationName:String
                        }
         401:Unauthorized
         403:Bad internet connection 
    /addFoundedPet/{id}
    post:
        description: Add location where a pet was found
                    aplication/JSONResponse:
                        {   petId:{petId}
                            lat:Float,
                            lon:Float,
                            locationName:String
                        }
        headers:  
        body: 
        responses: 
            200: 
                body: Location was added as "Find at"
            